config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :usuarios, as: :users, only: [:show,:update]
  # Routing with Devise
  devise_for :users
    # when the user within authenticate
  unauthenticated :user do
    devise_scope :user do
      root 'home#start', as: :start_root
    end
  end
    #When the user is authenticate
  authenticate :user do
    root 'home#index', as: :index_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id,uniqueness: {scope: :friend_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #Validations
  validates :name, presence: true,length: {in: 5..20}
  validates :lastName, presence: true, length: {in: 5..20}
  validates :email, uniqueness: true, length: {in: 5..50}
  # Publications
  has_many :posts
  has_attached_file :avatar, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_attached_file :cover, default_url: "/images/:style/missing_cover.jpg"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :lastName, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :lastName, :email, :password, :current_password)}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @post = Post.new
    @posts = Post.all
  end
  def start
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { render 'home/index', notice: 'Creado Con exito' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }


      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!, only: [:update]
  def show
    @post = Post.new
    @posts = Post.all
  end

  def update
    respond_to do |format|
      if    @user.update(user_params)
        format.html{ redirect_to @user}
      else
        format.html{ redirect_to @user,notice:"Error al enviar: #{@user.errors.full_messages}"}
      end
    end
  end
  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username,:email,:name,:lastName,:avatar,:cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<br/>
<div class="container">
    <div class="col-md-12">
        <%= render 'posts/form'%>
    </div>
  <% @posts.each do |post| %>
      <div class="container border border-danger rounded col-md-11 p-3 mt-2">
        <div class="row">
          <div class="col-md-1">

          </div>
          <div class="col-md-11 mt-2">
            <h5>
              <%= post.user_id %>
            </h5>
          </div>
        </div>
        <div class="col-md-12 mt-4">
          <%= post.body %>
        </div>
      </div>
  <%end %>
    <script>
        recargar = document.getElementById("recargar");
        recargar.addEventListener('click', ()=>{window.location.reload();
        })
    </script>
</div>

app/views/home/start.html.erb
<!-- Main Banner -->
<div class="container-fluid shadow p-3 mb-5 bg-white rounded">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="<%= asset_path '1.PNG' %>" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="<%= asset_path '2.PNG' %>" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="<%= asset_path '3.png' %>" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<!-- our venues-->
<h3 class="m-4"><span class="badge badge-danger">Nuestras Sedes</span></h3>
<div class="card-group m-4">
  <div class="card mr-1">
    <%= link_to "http://www.unilibrebaq.edu.co/unilibrebaq/", target: :_blank do %>
      <%= image_tag('barranquilla.png', class: 'card-img-top', alt: "Sede Barranquilla") %>
    <% end %>
  </div>
  <div class="card mr-1">
    <%= link_to "http://www.unilibre.edu.co/bogota/", target: :_blank do %>
      <%= image_tag('bogota.png', class: 'card-img-top', alt: "Sede Bogota") %>
    <% end %>
  </div>
  <div class="card mr-1">
    <%= link_to "https://www.unilibrecali.edu.co/index.php/en/", target: :_blank do %>
      <%= image_tag('cali.png', class: 'card-img-top', alt: "Sede Cali") %>
    <% end %>
  </div>
  <div class="card mr-1">
    <%= link_to "http://www.unilibre.edu.co/cartagena/", target: :_blank do %>
      <%= image_tag('cartagena.png', class: 'card-img-top', alt: "Sede Cartagena") %>
    <% end %>
  </div>
  <div class="card mr-1">
    <%= link_to "http://www.unilibrecucuta.edu.co/portal/", target: :_blank do %>
      <%= image_tag('cucuta.png', class: 'card-img-top', alt: "Sede Cucuta") %>
    <% end %>
  </div>
  <div class="card mr-1">
    <%= link_to "http://www.unilibre.edu.co/pereira/", target: :_blank do %>
      <%= image_tag('pereira.png', class: 'card-img-top', alt: "Sede Pereira") %>
    <% end %>
  </div>
  <div class="card">
    <%= link_to "http://www.unilibre.edu.co/socorro/", target: :_blank do %>
      <%= image_tag('socorro.png', class: 'card-img-top', alt: "Sede Socorro") %>
    <% end %>
  </div>
</div>
<br/><br/>
<!-- Footer -->
<footer class="page-footer font-small bg-danger pt-4">
  <div class="container">
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1 text-light">Registrate Gratis</h5>
      </li>
      <li class="list-inline-item">
        <%= link_to 'Registrarse  ', new_user_registration_path, class: 'btn btn-dark btn-rounded' %>
      </li>
    </ul>
  </div>
  <div class="footer-copyright text-center py-3 text-light border-top">
    <span>© 2020 Copyright: Juan Nicolas Hernandez Chavez</span>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

<body>
  <%= render 'shared/navbar' %>
  <% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger">
    <%= alert %>
  </p>
<% end %>
  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post,remote: true do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field form-group col-md-12" style="margin: 0 auto">
      <%= form.text_area :body ,class: 'col-md-12 shadow p-3 mb-3 rounded border', placeholder: '¿Que quieres compartir con la comunidad unilibrista?'%>
    </div>
    <div class="field form-group col-md-12">
      <%= form.submit :Compartir, class: 'btn btn-danger', id: "recargar"%>
    </div>
<% end %>
<style>
  .new_post{
      flex: 0 0 100%;
      max-width: 100%;
  }
</style>

app/views/posts/edit.html.erb
<br/>
<br/>
<%= render 'form', post: @post %>
<script>
    recargar = document.getElementById("recargar");
    recargar.addEventListener('click', ()=>{
        window.location.reload();
    })
</script>

app/views/posts/index.html.erb
<div class="container bg-danger rounded mt-5">
  <div class="col-md-12 p-4" >
    <h1 class="text-white" style="margin-left: 19%;">Has eliminado con exito tu publicación</h1>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<style>
  a:hover{
      background: none;
  }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-danger" >
    <a class="navbar-brand" href="/">
      <img src="<%= asset_path 'socialred.png'%>" width="220" height="70" alt="" loading="lazy">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item" >
          <a class="nav-link text-light" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Mi Perfil', current_user, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Editar Perfil', edit_user_registration_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item ">
            <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Iniciar sesion', new_user_session_path, class: 'nav-link text-light' %>
          </li>
        <%end %>
      </ul>
    </div>
  </nav>

app/views/usuarios/show.html.erb
 <div class="container shadow-lg col-md-6 mt-4" style="padding: 0">
    <div class="position-relative col-md-12" style="padding: 0">
      <%= image_tag @user.cover.url(), class: 'w-100', style: 'height:200px'%>
      <div class="position-absolute col-md-12" style="top: 0; padding: 0;">
        <div class="row" style="margin: 0">
          <div class="col-md-2" style="padding: 0">
            <%= image_tag @user.avatar.url(), class: 'float-left rounded-circle mt-5 ml-5 border border-dark', style: "width:105px; height:100px;"%>
          </div>
          <div class="col-md-8" style="padding: 0">
            <h1 class="text-white" style="margin-top: 11%; margin-left: 5%">
              <%= @user.name%>
              <%= @user.lastName%>
            </h1>
          </div>
          <div class="col-md-2" style="padding: 0">
            <%= link_to 'Editar perfil', edit_user_registration_path, class: 'btn btn-dark mt-2  ml-5 text-white'%>
          </div>
        </div>
      </div>
    </div>
   <div class="col-md-12 mt-4 mb-4">
     <%= render 'posts/form'%>
   </div>
   <br/>
   <% @posts.each do |post| %>
     <% if @user.id == post.user_id  %>
   <div class="container border border-danger rounded col-md-11 p-3 mt-2">
     <div class="row">
       <div class="col-md-1">
         <%= image_tag @user.avatar.url(), class: ' rounded-circle border border-dark', style: "width:50px; height:50px;"%>
       </div>
       <div class="col-md-10 mt-2">
         <h5>
           <%= @user.name%>
           <%= @user.lastName%>
         </h5>
       </div>
       <div class="col-md-1">
         <div class="dropdown">
           <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
           <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
             <%= link_to 'Eliminar Publicación', post, method: :delete, data: { confirm: 'Estas seguro de eliminar tu publicación'}, class: "dropdown-item"%>
             <%= link_to 'Editar Publicación', edit_post_path(post), class: "dropdown-item"%>
           </div>
         </div>
       </div>
     </div>
     <div class="col-md-12 mt-4">
       <%= post.body %>
     </div>
   </div>
     <%end %>
   <% end %>
   <br/>
   <br/>
   <script>
       recargar = document.getElementById("recargar");
       recargar.addEventListener('click', ()=>{
           window.location.reload();
       })
   </script>
 </div>